### ISSUE TITLE
Running on windows (vagrant) fails to complete

### ISSUE THREAD

**Issue by boxerone** [OpenDroneMap/odm_vagrant#9]
Hi all
thia is the error I got trying with "pacifica" set of data

"
Robust matching time : 0.000470876693726s
Full matching 1142 / 1143, time: 1.45251584053s
2015-11-30 19:50:19,584 reading features
2015-11-30 19:50:19,896 Merging features onto tracks
2015-11-30 19:50:20,147 Good tracks: 15854
images 12
nonfisheye images 12
0 partial reconstructions in total.
Traceback (most recent call last):
  File "/odm_app/OpenDroneMap/src/OpenSfM/bin/mesh", line 23, in <module>
    reconstructions = data.load_reconstruction()
  File "/odm_app/OpenDroneMap/src/OpenSfM/opensfm/dataset.py", line 291, in load_reconstruction
    with open(self.__reconstruction_file(filename)) as fin:
IOError: [Errno 2] No such file or directory: 'opensfm/reconstruction.json'
b

quitting cause:
        PYTHONPATH=/odm_app/OpenDroneMap/lib/python2.7/dist-packages "/odm_app/OpenDroneMap/src/OpenSfM/bin/run_all" ope
nsfm
returned with code 256.
"

**Comment by milamat** [comment]
I have the same problem with my data.. Could anybody please help?

**Comment by perotest** [comment]
I also have this problem.  I followed the "How to Install and Test" instructions and on Step 12 running with the test dataset.  Running Windows 8, Core i7 2.60 GHz, 16GB RAM, VirtualBox 5.0.16 r105871.  I'm a total noob so I'm probably in over my head and making a simple error following the "recipe".  May have to go with MapsMadeEasy because I'm no python troubleshooter for sure.

...
images 12
nonfisheye images 12
0 partial reconstructions in total.
Traceback (most recent call last):
  File "/odm_app/OpenDroneMap/src/OpenSfM/bin/mesh", line 23, in <module>
    reconstructions = data.load_reconstruction()
  File "/odm_app/OpenDroneMap/src/OpenSfM/opensfm/dataset.py", line 291, in load_reconstruction
    with open(self.__reconstruction_file(filename)) as fin:
IOError: [Errno 2] No such file or directory: 'opensfm/reconstruction.json'
b

quitting cause:
        PYTHONPATH=/odm_app/OpenDroneMap/lib/python2.7/dist-packages "/odm_app/OpenDroneMap/src/OpenSfM/bin/run_all" opensfm
returned with code 256.

**Comment by dakotabenjamin** [comment]
@milamat @boxerone @perotest 

Please update your ODM app by running 

```
git checkout master
git pull
```

and following these instructions to install: 

```
bash configure.sh
mkdir build && cd build && cmake .. && make && cd ..
```

Then you can run ODM from anywhere by calling 

```
./run.sh --project-path /absolute/path/to/your/project
```

you should place your images in a `images/` subdirectory for the new update to work.
